%va2modspec('bsim4_vappmod.va');
MOD = bsim4();
parmValList = {
                'parm_L', 1e-6,...
                'parm_W', 10e-6,...
                'parm_RSH', 10e-3,...
                'parm_NRS', 1,...
                'parm_NRD', 1,...
               };
MEO = model_dc_exerciser(MOD); % create a model exerciser object
                               % NOTE: press enter when prompted by MATLAB
Vdrain = 0:0.1:1; Vgate = 0:0.1:1; Vsource = 0; Vbulk = 0; % set bias values
MEO.plot('Idrain', Vdrain, Vgate, Vsource, Vbulk, parmValList{:}, MEO); % plot the drain current
