function cktnetlist = vbic_diffpair_ckt()
%function cktnetlist = vbic_diffpair_ckt()
%This function returns a cktnetlist structure for a BJT differential pair
%circuit.
% 
%The circuit
%  An ideal-ish differential pair using Vbic BJTs. The emitters of 2 BJTs
%  are connected at node nE (node voltage e_nE). An ideal current source of DC
%  value IE drains node E. The collector of the BJT on the left is connected to
%  node nCL; that of the one on the right to node nCR (node voltage e_nCR).
%  Resistors rL and rR connect from VCC to nodes nCL and nCR, respectively;
%  similarly with capacitors CL and CR. 
%  
%  The BJT on the left has its base connected to Vin; that of the one on the
%  right connects to ground. The circuit is, therefore, not perfectly
%  symmetric.
%
%  A sinusoidal transient input at frequency 1kHz is included in the circuit.
%
%Examples
%--------
%
% % set up DAE
% DAE =  MNA_EqnEngine(vbic_diffpair_ckt());
%
% % list all unknown names
% DAE.unknames(DAE) % equivalent to feval(DAE.unknames, DAE)
%
% % list all output names
% DAE.outputnames(DAE) % equivalent to feval(DAE.outputnames, DAE)
%
% % set up state outputs "manually"
% souts = StateOutputs(DAE);
% souts = souts.DeleteAll(souts);
% souts = souts.Add({'e_nCL', 'e_nCR', 'e_Vin', 'e_nE'}, souts);
%
% % run a DC operating point analysis
% dcop = dot_op(DAE);
% % print DC operating point
% feval(dcop.print, dcop);
%
% % run a DC DC sweep
% % feval(DAE.inputnames, DAE) shows 3 inputs: 'VCC:::E', 'Vin:::E', 'IE:::I'
% swp = dot_dcsweep(DAE, [], 'Vin:::E', -0.25:0.01:0.25);
% feval(swp.plot, swp);
%
% % get DC operating point solution vector
% qssSol = feval(dcop.getsolution, dcop);
%
% % AC analysis @ DC operating point; plot both DAE-defined and state outputs
% sweeptype = 'DEC'; fstart=1; fstop=1e5; nsteps=10;
% ltisss = dot_ac(DAE, qssSol, feval(DAE.uQSS, DAE), fstart, fstop,...
% nsteps, sweeptype);
% % plot frequency sweeps of system outputs
% feval(ltisss.plot, ltisss); % plot DAE-defined outputs
% feval(ltisss.plot, ltisss, souts); % plot state outputs
%
% % run transient and plot (both DAE-defined and state outputs)
% tstart = 0; tstep = 1e-5; tstop = 2e-3;
% TransObj = dot_transient(DAE, qssSol, tstart, tstep, tstop);
% feval(TransObj.plot, TransObj); % plot DAE-defined outputs 
% feval(TransObj.plot, TransObj, souts); % plot state outputs
%
%See also
%--------
% 
% add_element, supported_ModSpec_devices[TODO], DAEAPI, DAE_concepts,

%
%Author: Tianshi Wang, 2012/11/20
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Type "help MAPPlicense" at the MATLAB/Octave prompt to see the license      %
%% for this software.                                                          %
%% Copyright (C) 2008-2013 Jaijeet Roychowdhury <jr@berkeley.edu>. All rights  %
%% reserved.                                                                   %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    % ckt name
    cktnetlist.cktname = 'BJT diffpair with Vin- grounded';
    % nodes (names)
    cktnetlist.nodenames = {'nE', 'nCL', 'nCR', 'nCC', 'Vin'}; % non-ground 
                                % nodes
    cktnetlist.groundnodename = 'gnd';

    % circuit element values
    VCC = 5.0; % 5V
    VinDC = 0; % DC input value of Vin
    vinoft = @(t, args) args.A*sin(2*pi*args.f*t + args.phi); % transient 
                                                   % input function for Vin
    vinargs.A = 1; vinargs.f = 1e3; vinargs.phi = 0; % arguments for
                             % transient function
    IE = 2e-3;
    rL = 2000;
    rR = 2000;
    CL = 0.5e-6;
    CR = 0.5e-6;

    % Vbic parameters
    % the parameters below are taken from /vbic1.2/vbic_code/vbic_3T_et_xf/pars
    vbicParmList = {
    {'parm_TNOM',   27.0},...
    {'parm_RCX',    1.0},...
    {'parm_RCI',    1.0},...
    {'parm_VO',     0.0},...
    {'parm_GAMM',   0.0},...
    {'parm_HRCF',   0.0},...
    {'parm_RBX',    1.0},...
    {'parm_RBI',    1.0},...
    {'parm_RE',     1.0},...
    {'parm_RS',     1.0},...
    {'parm_RBP',    1.0},...
    {'parm_IS',     1.0e-16},...
    {'parm_NF',     1.0},...
    {'parm_NR',     1.0},...
    {'parm_FC',     0.9},...
    {'parm_CBEO',   0.0},...
    {'parm_CJE',    0.0},...
    {'parm_PE',     0.75},...
    {'parm_ME',     0.33},...
    {'parm_AJE',    -0.5},...
    {'parm_CBCO',   0.0},...
    {'parm_CJC',    0.0},...
    {'parm_QCO',    0.0},...
    {'parm_CJEP',   0.0},...
    {'parm_PC',     0.75},...
    {'parm_MC',     0.33},...
    {'parm_AJC',    -0.5},...
    {'parm_CJCP',   0.0},...
    {'parm_PS',     0.75},...
    {'parm_MS',     0.33},...
    {'parm_AJS',    -0.5},...
    {'parm_IBEI',   1.0e-18},...
    {'parm_WBE',    1.0},...
    {'parm_NEI',    1.0},...
    {'parm_IBEN',   0.0},...
    {'parm_NEN',    2.0},...
    {'parm_IBCI',   1.0e-16},...
    {'parm_NCI',    1.0},...
    {'parm_IBCN',   0.0},...
    {'parm_NCN',    2.0},...
    {'parm_AVC1',   0.0},...
    {'parm_AVC2',   0.0},...
    {'parm_ISP',    0.0},...
    {'parm_WSP',    1.0},...
    {'parm_NFP',    1.0},...
    {'parm_IBEIP',  0.0},...
    {'parm_IBENP',  0.0},...
    {'parm_IBCIP',  0.0},...
    {'parm_NCIP',   1.0},...
    {'parm_IBCNP',  0.0},...
    {'parm_NCNP',   2.0},...
    {'parm_VEF',    0.0},...
    {'parm_VER',    0.0},...
    {'parm_IKF',    0.0},...
    {'parm_IKR',    0.0},...
    {'parm_IKP',    0.0},...
    {'parm_TF',     0.0},...
    {'parm_QTF',    0.0},...
    {'parm_XTF',    0.0},...
    {'parm_VTF',    0.0},...
    {'parm_ITF',    0.0},...
    {'parm_TR',     0.0},...
    {'parm_TD',     0.0},...
    {'parm_KFN',    0.0},...
    {'parm_AFN',    1.0},...
    {'parm_BFN',    1.0},...
    {'parm_XRE',    0},...
    {'parm_XRBI',   0},...
    {'parm_XRCI',   0},...
    {'parm_XRS',    0},...
    {'parm_XVO',    0},...
    {'parm_EA',     1.12},...
    {'parm_EAIE',   1.12},...
    {'parm_EAIC',   1.12},...
    {'parm_EAIS',   1.12},...
    {'parm_EANE',   1.12},...
    {'parm_EANC',   1.12},...
    {'parm_EANS',   1.12},...
    {'parm_XIS',    3.0},...
    {'parm_XII',    3.0},...
    {'parm_XIN',    3.0},...
    {'parm_TNF',    0.0},...
    {'parm_TAVC',   0.0},...
    {'parm_RTH',    1.0},...
    {'parm_CTH',    0.0},...
    {'parm_VRT',    0.0},...
    {'parm_ART',    0.1},...
    {'parm_CCSO',   0.0},...
    {'parm_QBM',    0.0},...
    {'parm_NKF',    0.5},...
    {'parm_XIKF',   0},...
    {'parm_XRCX',   0},...
    {'parm_XRBX',   0},...
    {'parm_XRBP',   0},...
    {'parm_ISRR',   1.0},...
    {'parm_XISR',   0.0},...
    {'parm_DEAR',   0.0},...
    {'parm_EAP',    1.12},...
    {'parm_VBBE',   0.0},...
    {'parm_NBBE',   1.0},...
    {'parm_IBBE',   1.0e-6},...
    {'parm_TVBBE1', 0.0},...
    {'parm_TVBBE2', 0.0},...
    {'parm_TNBBE',  0.0},...
    {'parm_EBBE',   0.0},...
    {'parm_DTEMP',  0.0},...
    {'parm_VERS',   1.2},...
    {'parm_VREV',   0.0},...
    };

    cktnetlist = add_element(cktnetlist, vsrcModSpec(), 'VCC', {'nCC', 'gnd'}, {},         {{'E' {'DC', VCC}}});
    %                         ^         ^            ^          ^          ^                  ^
    %                      cktnetlist, ModSpec model, name       nodes  , parameters,    DC/transient/AC values of internal sources
    %                                                 []=defaults,     optional args

    cktnetlist = add_element(cktnetlist, resModSpec(), 'rL', {'nCC', 'nCL'}, ...
                      {{'R', rL}}, {});
    cktnetlist = add_element(cktnetlist, resModSpec(), 'rR', {'nCC', 'nCR'}, ...
                  rR, {});
    cktnetlist = add_element(cktnetlist, capModSpec(), 'CL', {'nCC', 'nCL'}, ...
                      {{'C', CL}});
    cktnetlist = add_element(cktnetlist, capModSpec(), 'CR', {'nCC', 'nCR'}, CR);
    cktnetlist = add_element(cktnetlist, vbic(), 'QL', {'nCL', 'Vin', 'nE'}, vbicParmList);
    cktnetlist = add_element(cktnetlist, vbic(), 'QR', {'nCR', 'gnd', 'nE'}, vbicParmList);
    cktnetlist = add_element(cktnetlist, vsrcModSpec(), 'Vin', {'Vin', 'gnd'}, {},         {{'E', {'DC', VinDC}, {'AC' 1}, {'tr', vinoft, vinargs}}});
    %                               ^          ^           ^           ^        ^                    ^      ^        ^
    %                            cktnetlist, ModSpec model, name       nodes  , parameters,    DC/transient values of internal sources
    %                                                 []=defaults,     optional args
    cktnetlist = add_element(cktnetlist, isrcModSpec(), 'IE', {'nE', 'gnd'}, {},         {{'I', {'DC', IE}}});
    %                             ^          ^           ^           ^       ^                  ^      ^        ^
    %                          cktnetlist, ModSpec model, name       nodes  , parameters,    DC/transient values of internal sources
    %                                                 []=defaults,     optional args

    cktnetlist = add_output(cktnetlist, 'Vin');
    cktnetlist = add_output(cktnetlist, 'nE');
    cktnetlist = add_output(cktnetlist, 'nCL');
    cktnetlist = add_output(cktnetlist, 'nCR');
    cktnetlist = add_output(cktnetlist, 'nCL', 'nCR');
    cktnetlist = add_output(cktnetlist, 'i(Vin)', 1e5);

end
